version: "3.1"

language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: DucklingEntityExtractor
  dimensions: ["time", "date"]

policies:
- name: RulePolicy
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
  fallback_score: 0.3

- name: MemoizationPolicy
  max_history: 5

- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20241109-211640-advanced-sidebar
